import type { Provider, Settings } from "./types.ts";

export const SETTINGS: Settings = {
  region: localStorage.getItem("region") || "US",
  openInNewTab: JSON.parse(localStorage.getItem("openInNewTab") ?? "true"),
  pinned: JSON.parse(localStorage.getItem("pinnedProviders") || "[]"),
  defaultProvider: localStorage.getItem("defaultProvider") || null,
};

export const PROVIDERS: Provider[] = [
  {
    id: "imdb",
    name: "IMDb",
    url: "https://www.imdb.com/find/?q={q}",
    types: ["movie", "tv"],
    aliases: ["!imdb", "!i"],
    icon: "https://www.google.com/s2/favicons?domain=imdb.com",
  },
  {
    id: "letterboxd",
    name: "Letterboxd",
    url: "https://letterboxd.com/search/{q}",
    types: ["movie"],
    aliases: ["!lb", "!letterboxd"],
    icon: "https://www.google.com/s2/favicons?domain=letterboxd.com",
  },
  {
    id: "tmdb",
    name: "TMDb",
    url: "https://www.themoviedb.org/search?query={q}",
    types: ["movie", "tv"],
    aliases: ["!tmdb"],
    icon: "https://www.google.com/s2/favicons?domain=themoviedb.org",
  },
  {
    id: "trakt",
    name: "Trakt",
    url: "https://trakt.tv/search?query={q}",
    types: ["movie", "tv"],
    aliases: ["!trakt"],
    icon: "https://www.google.com/s2/favicons?domain=trakt.tv",
  },
  {
    id: "opencritic",
    name: "OpenCritic",
    url: "https://opencritic.com/search?q={q}",
    types: ["game"],
    aliases: ["!oc", "!opencritic"],
    icon: "https://www.google.com/s2/favicons?domain=opencritic.com",
  },
  {
    id: "metacritic",
    name: "Metacritic (Games)",
    url: "https://www.metacritic.com/search/{q}/",
    types: ["game"],
    aliases: ["!mc", "!metacritic"],
    icon: "https://www.google.com/s2/favicons?domain=metacritic.com",
  },
  {
    id: "justwatch",
    name: "JustWatch",
    url: () =>
      `https://www.justwatch.com/${SETTINGS.region.toLowerCase()}/search?q={q}`,
    types: ["movie", "tv"],
    aliases: ["!jw", "!justwatch"],
    icon: "https://www.google.com/s2/favicons?domain=justwatch.com",
  },
  {
    id: "rt",
    name: "Rotten Tomatoes",
    url: "https://www.rottentomatoes.com/search?search={q}",
    types: ["movie", "tv"],
    aliases: ["!rt"],
    icon: "https://www.google.com/s2/favicons?domain=rottentomatoes.com",
  },
  {
    id: "wikipedia",
    name: "Wikipedia",
    url: "https://en.wikipedia.org/w/index.php?search={q}",
    types: ["general"],
    aliases: ["!w", "!wp"],
    icon: "https://www.google.com/s2/favicons?domain=en.wikipedia.org",
  },
  {
    id: "kagi",
    name: "Kagi",
    url: "https://kagi.com/search?q={q}",
    types: ["general"],
    aliases: ["!k"],
    icon: "https://www.google.com/s2/favicons?domain=kagi.com",
  },
  {
    id: "ddg",
    name: "DuckDuckGo",
    url: "https://duckduckgo.com/?q={q}",
    types: ["general"],
    aliases: ["!ddg"],
    icon: "https://www.google.com/s2/favicons?domain=duckduckgo.com",
  },
  {
    id: "google",
    name: "Google",
    url: "https://www.google.com/search?q={q}",
    types: ["general"],
    aliases: ["!g"],
    icon: "https://www.google.com/s2/favicons?domain=google.com",
  },
  {
    id: "youtube",
    name: "YouTube",
    url: "https://www.youtube.com/results?search_query={q}",
    types: ["general"],
    aliases: ["!yt"],
    icon: "https://www.google.com/s2/favicons?domain=youtube.com",
  },
  {
    id: "github",
    name: "GitHub",
    url: "https://github.com/search?q={q}",
    types: ["code"],
    aliases: ["!gh"],
    icon: "https://www.google.com/s2/favicons?domain=github.com",
  },
  {
    id: "stackoverflow",
    name: "Stack Overflow",
    url: "https://stackoverflow.com/search?q={q}",
    types: ["code"],
    aliases: ["!so"],
    icon: "https://www.google.com/s2/favicons?domain=stackoverflow.com",
  },
  {
    id: "myanimelist",
    name: "MyAnimeList",
    url: "https://myanimelist.net/anime.php?q={q}",
    types: ["anime"],
    aliases: ["!mal"],
    icon: "https://www.google.com/s2/favicons?domain=myanimelist.net",
  },
  {
    id: "goodreads",
    name: "Goodreads",
    url: "https://www.goodreads.com/search?q={q}",
    types: ["book"],
    aliases: ["!gr"],
    icon: "https://www.google.com/s2/favicons?domain=goodreads.com",
  },
  {
    id: "spotify",
    name: "Spotify",
    url: "http://open.spotify.com/search/{q}",
    types: ["music"],
    aliases: ["!sp"],
    icon: "https://www.google.com/s2/favicons?domain=spotify.com",
  },
  {
    id: "applepodcasts",
    name: "Apple Podcasts",
    url: "https://itunes.apple.com/search?term={q}&entity=podcast",
    types: ["podcast"],
    aliases: ["!ap"],
    icon: "https://www.google.com/s2/favicons?domain=apple.com",
  },
  {
    id: "boardgamegeek",
    name: "BoardGameGeek",
    url: "https://boardgamegeek.com/geeksearch.php?action=search&objecttype=boardgame&q={q}",
    types: ["boardgame"],
    aliases: ["!bgg"],
    icon: "https://www.google.com/s2/favicons?domain=boardgamegeek.com",
  },
];

